apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  APP_ENV: {{ .Values.config.appEnv | quote }}
  NATS_URL: {{ .Values.config.natsURL | quote }}
  OO_ENDPOINT: {{ .Values.config.ooEndpoint | quote }}
  OO_SERVICE_NAME: {{ .Values.config.ooServiceName | quote }}
  OO_ENVIRONMENT: {{ .Values.config.ooEnvironment | quote }}
  OO_SAMPLE_RATE: {{ .Values.config.ooSampleRate | quote }}
  MPESA_SHORTCODE: {{ .Values.config.mpesaShortCode | quote }}
  MPESA_CALLBACK_BASE_URL: {{ .Values.config.mpesaCallbackBaseURL | quote }}

