{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseURL | quote }}
  REDIS_URL: {{ .Values.secret.redisURL | quote }}
  HMAC_SIGNING_SECRET: {{ .Values.secret.hmacSigningSecret | quote }}
  OO_EMAIL: {{ .Values.secret.ooEmail | quote }}
  OO_PASSWORD: {{ .Values.secret.ooPassword | quote }}
  MPESA_CONSUMER_KEY: {{ .Values.secret.mpesaConsumerKey | quote }}
  MPESA_CONSUMER_SECRET: {{ .Values.secret.mpesaConsumerSecret | quote }}
  MPESA_PASSKEY: {{ .Values.secret.mpesaPassKey | quote }}
  MPESA_B2C_INITIATOR_NAME: {{ .Values.secret.mpesaB2cInitiatorName | quote }}
  MPESA_B2C_SECURITY_CREDENTIAL: {{ .Values.secret.mpesaB2cSecurityCredential | quote }}
  KCB_CONSUMER_KEY: {{ .Values.secret.kcbConsumerKey | quote }}
  KCB_CONSUMER_SECRET: {{ .Values.secret.kcbConsumerSecret | quote }}
  PAYSTACK_SECRET_KEY: {{ .Values.secret.paystackSecretKey | quote }}
  PAYSTACK_PUBLIC_KEY: {{ .Values.secret.paystackPublicKey | quote }}
  PAYSTACK_WEBHOOK_KEY: {{ .Values.secret.paystackWebhookKey | quote }}
  PESALINK_API_KEY: {{ .Values.secret.pesalinkApiKey | quote }}
  PESALINK_API_SECRET: {{ .Values.secret.pesalinkApiSecret | quote }}
{{- end }}
